// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrucsmhbmaHkXYIUdVHTXuIIEY_5A2PJk',
    appId: '1:1062684967635:web:39f058d517295e48fa8a26',
    messagingSenderId: '1062684967635',
    projectId: 'umkm-project-mobile',
    authDomain: 'umkm-project-mobile.firebaseapp.com',
    storageBucket: 'umkm-project-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJDus6M-NG_8_ivdRwAKDN2YtZAT-wf4Q',
    appId: '1:1062684967635:android:cc9fff3ac57d3377fa8a26',
    messagingSenderId: '1062684967635',
    projectId: 'umkm-project-mobile',
    storageBucket: 'umkm-project-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_LNqdrNEWI4B3aSz8X3Bl_hxe6DiR95Q',
    appId: '1:1062684967635:ios:c3f899e3ca96722cfa8a26',
    messagingSenderId: '1062684967635',
    projectId: 'umkm-project-mobile',
    storageBucket: 'umkm-project-mobile.firebasestorage.app',
    iosBundleId: 'com.example.projectUmkm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_LNqdrNEWI4B3aSz8X3Bl_hxe6DiR95Q',
    appId: '1:1062684967635:ios:c3f899e3ca96722cfa8a26',
    messagingSenderId: '1062684967635',
    projectId: 'umkm-project-mobile',
    storageBucket: 'umkm-project-mobile.firebasestorage.app',
    iosBundleId: 'com.example.projectUmkm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrucsmhbmaHkXYIUdVHTXuIIEY_5A2PJk',
    appId: '1:1062684967635:web:b2ad71fc86571ccbfa8a26',
    messagingSenderId: '1062684967635',
    projectId: 'umkm-project-mobile',
    authDomain: 'umkm-project-mobile.firebaseapp.com',
    storageBucket: 'umkm-project-mobile.firebasestorage.app',
  );

}